version: '3.9'
services:
  web:
    image: srv-spring-admin:latest
    networks:
      - schambeck-net
    environment:
      - SERVER_PORT=9999
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
    ports:
      - "9999:9999"
networks:
  schambeck-net:
    driver: bridge
